### ISSUE TITLE
Crash when trying to batch download if yt-dl not found

### ISSUE THREAD

**Issue by megabugman** [murrty/SoloMatchmaking#4]
Feel free to copy + paste this entire text wall into a new issue on Github

Version: 2,24
Reported Exception: An exception occured
Message: No process is associated with this object.
Stacktrace:    at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at youtube_dl_gui.frmDownloader.CloseForm()
Source: System
TargetSite: Void EnsureState(State)
Full report:
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at youtube_dl_gui.frmDownloader.CloseForm()

**Comment by megabugman** [comment]
So, I just noticed, pressig Open Github opens this/incorrect repository, hence please move this second bug report to the correct repo 
![bug](https://user-images.githubusercontent.com/17204819/88475193-ffc80d00-cf2d-11ea-81fc-d419cdd52b27.png)
youtube-dl-gui

**Comment by murrty** [comment]
if you still have this issue, reopen in the other repo, hopefully with more information on what lead up to the error since it only tells me what method caused it

**Comment by murrty** [comment]
if you still have the issue, reopen in the other repo
